name: CTPhotography
favicon: null
layout_spectrum: 0.9406207611318678
typography_spectrum: 0.6164167209062725
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.36388808116316795
  lightness: 0.19785002782009542
  saturation: 0.35569044249132276
  rhythmicContrast: 0.28299275250174105
purpose: []
